function net = initializeFull3DCNN()

f=1/100 ;
net.layers = {} ;
net.layers{end+1} = struct('type', 'conv3D', ...
                           'filters', f*randn(201,201,7,1,10, 'single'), ...
                           'biases', zeros(1, 10, 'single'), ...
                           'stride', 1, ...
                           'pad', 0) ;
% net.layers{end+1} = struct('type', 'pool3D', ...
%                            'method', 'max', ...
%                            'pool', [2 2 2], ...
%                            'stride', [1 1 1], ...
%                            'pad', [0,0,  0,0, 0,0]) ;
                       net.layers{end+1} = struct('type', 'relu') ;
%                        net.layers{end+1} = struct('type', 'conv3D', ...
%                            'filters', f*randn(5,5,1,10,50, 'single'), ...
%                            'biases', zeros(1, 50, 'single'), ...
%                            'stride', 1, ...
%                            'pad', 0) ;
                        net.layers{end+1} = struct('type', 'conv3D', ...
                           'filters', f*randn(312,312,69,10,3, 'single'), ...
                           'biases', zeros(1, 3, 'single'), ...
                           'stride', 1, ...
                           'pad', 0) ;
%                                               net.layers{end+1} = struct('type', 'relu') ;

%                         net.layers{end+1} = struct('type', 'conv3D', ...
%                            'filters', f*randn(5,5,3,500,3, 'single'), ...
%                            'biases', zeros(1, 3, 'single'), ...
%                            'stride', 1, ...
%                            'pad', 0) ;
 net.layers{end+1} = struct('type', 'softmaxloss3D') ;

% net.layers{end+1} = struct('type', 'conv3D', ...
%                            'filters', f*randn(5,5,20,50, 'single'),...
%                            'biases', zeros(1,50,'single'), ...
%                            'stride', 1, ...
%                            'pad', 0) ;
% net.layers{end+1} = struct('type', 'pool3D', ...
%                            'method', 'max', ...
%                            'pool', [2 2 2], ...
%                            'stride', [1 1 1], ...
%                            'pad', 0) ;
% net.layers{end+1} = struct('type', 'conv', ...
%                            'filters', f*randn(4,4,50,500, 'single'),...
%                            'biases', zeros(1,500,'single'), ...
%                            'stride', 1, ...
%                            'pad', 0) ;
% net.layers{end+1} = struct('type', 'relu') ;
% net.layers{end+1} = struct('type', 'conv', ...
%                            'filters', f*randn(2,2,500,26, 'single'),...
%                            'biases', zeros(1,26,'single'), ...
%                            'stride', 1, ...
%                            'pad', 0) ;
% net.layers{end+1} = struct('type', 'softmaxloss') ;